stack_overflow/config/routes.rb
Rails.application.routes.draw do

   root 'questions#index'

    resources :questions do
      member do
        put 'upvote'
        put 'downvote'
      end
      resources :answers do
        member do
          put 'upvote'
          put 'downvote'
        end
      end
    end

end

stack_overflow/app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question

  def upvotes
    self.votes += 1
    self.save
  end

  def downvotes
    self.votes -= 1
    self.save
  end
end

stack_overflow/app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers

  def upvotes
    self.votes += 1
    self.save
  end

  def downvotes
    self.votes -= 1
    self.save
  end
end

stack_overflow/app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    p params
    @question = Question.find(params[:question_id])
    @answer = Answer.create!(title: params[:answer][:title],
                         content: params[:answer][:content],
                         question_id: @question.id)

    # redirect_to question_path(@question)
    render json: @answer
  end

  def edit
    @answer = Answer.find(params[:id])
    @question = Question.find(params[:question_id])
  end

  def update
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    @answer.update(title: params[:answer][:title],
                   content: params[:answer][:content])

    redirect_to @question
  end

  def destroy
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    @answer.destroy

    redirect_to @question
  end

  def upvote
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    @answer.upvotes

    redirect_to question_path(@question)
  end

  def downvote
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    @answer.downvotes

    redirect_to question_path(@question)
  end


end

stack_overflow/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

stack_overflow/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all.sort
    @question = Question.new
  end

  def create
    @question = Question.new(title: params[:question][:title],
                             content: params[:question][:content])

    if @question.save
      # redirect_to root_path
      render json: {question: @question}
    end
  end

  def show
    @question = Question.find(params[:id])
    @answers = Answer.where(question_id: params[:id]).sort
    @answer = Answer.new
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(title: params[:question][:title],
                     content: params[:question][:content])

      redirect_to question_path(@question)
    else
      redirect_to edit_question_path
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    redirect_to root_path
  end

  def upvote
    @question = Question.find(params[:id])
    @question.upvotes

    redirect_to root_path
  end

  def downvote
    @question = Question.find(params[:id])
    @question.downvotes

    redirect_to root_path
  end

end

stack_overflow/app/helpers/answers_helper.rb
module AnswersHelper
end

stack_overflow/app/helpers/application_helper.rb
module ApplicationHelper
end

stack_overflow/app/helpers/questions_helper.rb
module QuestionsHelper
end

stack_overflow/app/views/answers/edit.html.erb
<h2>Edit <%= @answer.title %></h2>

<%= form_for [@question, @answer] do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :content %>
    <%= f.text_field :content %>
    <%= f.submit "Edit" %>
<% end %>

stack_overflow/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StackOverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

stack_overflow/app/views/questions/edit.html.erb
<h2>Edit <%= @question.title %></h2>

<%= form_for @question do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :content %>
    <%= f.text_field :content %>
    <%= f.submit "Edit" %>
<% end %>

stack_overflow/app/views/questions/index.html.erb
<h2>Questions:</h2>
<div class ="question-wrapper">
<% @questions.each do |question| %>
  <div class ="question-container">
    <a href ="/questions/<%= question.id %>"><p id="question-title"><%= question.title %></p></a>
    <p id ="q_votes">Votes: <%= question.votes %></p>
    <p><%= button_to 'Upvote', upvote_question_path(question.id), method: :put, :form => {:id => "upvote_button"} %>
      <%= button_to 'Downvote', downvote_question_path(question.id),
      method: :put, :form => {:id => "downvote_button"} %></p>
  </div>
<% end %>
</div>

<h2>Add a question</h2>
<%= form_for @question, :html => {:id => "new_question_form"} do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

stack_overflow/app/views/questions/show.html.erb
<div>
  <h3><%= @question.title %></h3>

  <p><%= @question.content %>
<%= button_to 'Delete', question_path(@question), method: :delete %>
<%= button_to 'Edit', edit_question_path(@question), method: :get %></p>
</div>

<div class = "answer-wrapper" >
  <% @answers.each do |answer| %>
  <div class ="answer-container">
    <p id="answer-title">Title: <%= answer.title %></p>
    <p id="answer-content">Content: <%= answer.content %></p>
    <p id="a_votes">Votes: <%= answer.votes %></p>
    <p><%= button_to 'Upvote', upvote_question_answer_path(@question,answer.id), method: :put, :form => {:id => "a_upvote_button"} %>
      <%= button_to 'Downvote', downvote_question_answer_path(@question, answer.id), method: :put, :form => {:id => "a_downvote_button"} %></p>
    <p><%= button_to 'Delete', question_answer_path(@question, answer.id), method: :delete, :form => {:id => "delete_button"} %>
   <%= button_to 'Edit', edit_question_answer_path(@question, answer.id), method: :get, :form => {:id => "edit_button"} %></p>
  </div>
  <% end %>
</div><br>


<div>
  <h2>Add answers</h2>
  <%= form_for [@question, @answer], :html => {:id => "new_answer_form"} do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :content %>
    <%= f.text_field :content %>
    <%= f.submit "Submit an answer" %>
  <% end %>
</div>

<p><%= button_to 'Back to Home Page', questions_path, method: :get %></p>